OPTION(PICLAS_BUILD_POSTI "No help, variable specified on the command line." ON)
OPTION(PICLAS_CODE_ANALYZE "Code Analyze" OFF)
SET(PICLAS_EQNSYSNAME "poisson" CACHE STRING "No help, variable specified on the command line.")
OPTION(PICLAS_EXTRAE "Extrae instrumentation for code profiling (event tracing)" OFF)
SET(PICLAS_INSTRUCTION "-march=x86-64-v2 -mtune=generic" CACHE STRING "Compiler optimization options")
SET(PICLAS_IPO "FALSE" CACHE STRING "No help, variable specified on the command line.")
OPTION(PICLAS_PERFORMANCE "Enable performance optimizations (e.g. PGO for GNU)" OFF)
OPTION(PICLAS_READIN_CONSTANTS "Allow read-in of user-defined constants, such as the vacuum speed of light c0, permittivity eps and permeability mu." ON)
SET(PICLAS_TIMEDISCMETHOD "Leapfrog" CACHE STRING "No help, variable specified on the command line.")
OPTION(PICLAS_UNITTESTS "No help, variable specified on the command line." OFF)
SET(HDF5_DIR "C:/msys64/ucrt64/lib/cmake/hdf5" CACHE STRING "No help, variable specified on the command line.")
SET(HDF5_Fortran_INCLUDE_DIR "C:/msys64/ucrt64/include" CACHE STRING "No help, variable specified on the command line.")
SET(HDF5_ROOT "C:/msys64/ucrt64" CACHE STRING "No help, variable specified on the command line.")
SET(CMAKE_ADDR2LINE "C:/msys64/ucrt64/bin/addr2line.exe" CACHE STRING "Path to a program.")
SET(CMAKE_AR "C:/msys64/ucrt64/bin/ar.exe" CACHE STRING "Path to a program.")
SET(CMAKE_BUILD_TYPE "Release" CACHE STRING "Choose the type of build, options are: None Debug Release RelWithDebInfo MinSizeRel ...")
OPTION(CMAKE_COLOR_DIAGNOSTICS "Flag if CMake should attempt to color output" ON)
SET(CMAKE_COMMAND "C:/msys64/ucrt64/bin/cmake.exe" CACHE STRING "Path to CMake executable.")
SET(CMAKE_CPACK_COMMAND "C:/msys64/ucrt64/bin/cpack.exe" CACHE STRING "Path to cpack program executable.")
SET(CMAKE_CTEST_COMMAND "C:/msys64/ucrt64/bin/ctest.exe" CACHE STRING "Path to ctest program executable.")
SET(CMAKE_CXX_COMPILER "C:/msys64/ucrt64/bin/g++.exe" CACHE STRING "CXX compiler")
SET(CMAKE_CXX_COMPILER_AR "C:/msys64/ucrt64/bin/gcc-ar.exe" CACHE STRING "A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler")
SET(CMAKE_CXX_COMPILER_RANLIB "C:/msys64/ucrt64/bin/gcc-ranlib.exe" CACHE STRING "A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler")
SET(CMAKE_CXX_FLAGS_DEBUG "-g" CACHE STRING "Flags used by the CXX compiler during DEBUG builds.")
SET(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -DNDEBUG" CACHE STRING "Flags used by the CXX compiler during MINSIZEREL builds.")
SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG" CACHE STRING "Flags used by the CXX compiler during RELEASE builds.")
SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG" CACHE STRING "Flags used by the CXX compiler during RELWITHDEBINFO builds.")
SET(CMAKE_CXX_STANDARD_LIBRARIES "-lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32" CACHE STRING "Libraries linked by default with all C++ applications.")
SET(CMAKE_C_COMPILER "C:/msys64/ucrt64/bin/gcc.exe" CACHE STRING "C compiler")
SET(CMAKE_C_COMPILER_AR "C:/msys64/ucrt64/bin/gcc-ar.exe" CACHE STRING "A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler")
SET(CMAKE_C_COMPILER_RANLIB "C:/msys64/ucrt64/bin/gcc-ranlib.exe" CACHE STRING "A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler")
SET(CMAKE_C_FLAGS_DEBUG "-g" CACHE STRING "Flags used by the C compiler during DEBUG builds.")
SET(CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG" CACHE STRING "Flags used by the C compiler during MINSIZEREL builds.")
SET(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG" CACHE STRING "Flags used by the C compiler during RELEASE builds.")
SET(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG" CACHE STRING "Flags used by the C compiler during RELWITHDEBINFO builds.")
SET(CMAKE_C_STANDARD_LIBRARIES "-lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32" CACHE STRING "Libraries linked by default with all C applications.")
SET(CMAKE_DLLTOOL "C:/msys64/ucrt64/bin/dlltool.exe" CACHE STRING "Path to a program.")
SET(CMAKE_EXECUTABLE_FORMAT "Unknown" CACHE STRING "Executable file format")
SET(CMAKE_FIND_PACKAGE_REDIRECTS_DIR "C:/Data/PRJ/Piclas/leap/CMakeFiles/pkgRedirects" CACHE STRING "Value Computed by CMake.")
SET(CMAKE_FQDN_HOST "PowerMachine" CACHE STRING "")
SET(CMAKE_Fortran_COMPILER "C:/msys64/ucrt64/bin/gfortran.exe" CACHE STRING "Fortran compiler")
SET(CMAKE_Fortran_COMPILER_AR "C:/msys64/ucrt64/bin/gcc-ar.exe" CACHE STRING "A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler")
SET(CMAKE_Fortran_COMPILER_RANLIB "C:/msys64/ucrt64/bin/gcc-ranlib.exe" CACHE STRING "A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler")
SET(CMAKE_Fortran_FLAGS " -fdefault-real-8 -fdefault-double-8 -fbackslash -ffree-line-length-0 -Wno-lto-type-mismatch -DGNU" CACHE STRING "Default compiler flags")
SET(CMAKE_Fortran_FLAGS_DEBUG " -fdefault-real-8 -fdefault-double-8 -fbackslash -ffree-line-length-0 -Wno-lto-type-mismatch -DGNU -g  -Og -ggdb3 -ffpe-trap=invalid,zero,overflow -fbounds-check -fbacktrace -Wall" CACHE STRING "Debug compiler flags")
SET(CMAKE_Fortran_FLAGS_MINSIZEREL "-Os" CACHE STRING "Flags used by the Fortran compiler during MINSIZEREL builds.")
SET(CMAKE_Fortran_FLAGS_NOGPROFILE " -fdefault-real-8 -fdefault-double-8 -fbackslash -ffree-line-length-0 -Wno-lto-type-mismatch -DGNU -g1 -O3 -march=x86-64-v2 -mtune=generic -fno-inline -fno-optimize-sibling-calls" CACHE STRING "NoGProfile compiler flags")
SET(CMAKE_Fortran_FLAGS_PROFILE " -fdefault-real-8 -fdefault-double-8 -fbackslash -ffree-line-length-0 -Wno-lto-type-mismatch -DGNU -pg -O3 -march=x86-64-v2 -mtune=generic -finline-functions" CACHE STRING "Profile compiler flags")
SET(CMAKE_Fortran_FLAGS_RELEASE " -fdefault-real-8 -fdefault-double-8 -fbackslash -ffree-line-length-0 -Wno-lto-type-mismatch -DGNU     -O3 -march=x86-64-v2 -mtune=generic -finline-functions" CACHE STRING "Release compiler flags")
SET(CMAKE_Fortran_FLAGS_RELWITHDEBINFO "-O2 -g" CACHE STRING "Flags used by the Fortran compiler during RELWITHDEBINFO builds.")
SET(CMAKE_Fortran_FLAGS_SANITIZE " -fdefault-real-8 -fdefault-double-8 -fbackslash -ffree-line-length-0 -Wno-lto-type-mismatch -DGNU -g  -Og -ggdb3 -ffpe-trap=invalid,zero,overflow,denorm -fbounds-check -fbacktrace -Wall -fno-omit-frame-pointer -Wc-binding-type -Wuninitialized -pedantic" CACHE STRING "Sanitize compiler flags")
SET(CMAKE_GENERATOR "Ninja" CACHE STRING "Name of generator.")
OPTION(CMAKE_GNUtoMS "Convert GNU import libraries to MS format (requires Visual Studio)" OFF)
SET(CMAKE_HOME_DIRECTORY "C:/Data/PRJ/Piclas/piclas-master" CACHE STRING "Source directory with the top level CMakeLists.txt file for this project")
SET(CMAKE_INSTALL_BINDIR "bin" CACHE STRING "User executables (bin)")
SET(CMAKE_INSTALL_DATADIR "share" CACHE STRING "Read-only architecture-independent data (DATAROOTDIR)")
SET(CMAKE_INSTALL_DATAROOTDIR "share" CACHE STRING "Read-only architecture-independent data root (share)")
SET(CMAKE_INSTALL_DOCDIR "share/doc/PICLas" CACHE STRING "Documentation root (DATAROOTDIR/doc/PROJECT_NAME)")
SET(CMAKE_INSTALL_INCLUDEDIR "include" CACHE STRING "C header files (include)")
SET(CMAKE_INSTALL_INFODIR "share/info" CACHE STRING "Info documentation (DATAROOTDIR/info)")
SET(CMAKE_INSTALL_LIBDIR "lib" CACHE STRING "Object code libraries (lib)")
SET(CMAKE_INSTALL_LIBEXECDIR "libexec" CACHE STRING "Program executables (libexec)")
SET(CMAKE_INSTALL_LOCALEDIR "share/locale" CACHE STRING "Locale-dependent data (DATAROOTDIR/locale)")
SET(CMAKE_INSTALL_LOCALSTATEDIR "var" CACHE STRING "Modifiable single-machine data (var)")
SET(CMAKE_INSTALL_MANDIR "share/man" CACHE STRING "Man documentation (DATAROOTDIR/man)")
SET(CMAKE_INSTALL_OLDINCLUDEDIR "/usr/include" CACHE STRING "C header files for non-gcc (/usr/include)")
SET(CMAKE_INSTALL_PREFIX "C:/Data/PRJ/Piclas/piclas-master" CACHE STRING "Prefix prepended to install directories")
SET(CMAKE_INSTALL_RUNSTATEDIR "var/run" CACHE STRING "Run-time variable data (LOCALSTATEDIR/run)")
SET(CMAKE_INSTALL_SBINDIR "sbin" CACHE STRING "System admin executables (sbin)")
SET(CMAKE_INSTALL_SHAREDSTATEDIR "com" CACHE STRING "Modifiable architecture-independent data (com)")
SET(CMAKE_INSTALL_SYSCONFDIR "etc" CACHE STRING "Read-only single-machine data (etc)")
SET(CMAKE_LINKER "C:/msys64/ucrt64/bin/ld.exe" CACHE STRING "Path to a program.")
SET(CMAKE_LIST_FILE_NAME "CMakeLists.txt" CACHE STRING "Name of CMakeLists files to read")
SET(CMAKE_MAKE_PROGRAM "C:/msys64/ucrt64/bin/ninja.exe" CACHE STRING "No help, variable specified on the command line.")
SET(CMAKE_NM "C:/msys64/ucrt64/bin/nm.exe" CACHE STRING "Path to a program.")
SET(CMAKE_OBJCOPY "C:/msys64/ucrt64/bin/objcopy.exe" CACHE STRING "Path to a program.")
SET(CMAKE_OBJDUMP "C:/msys64/ucrt64/bin/objdump.exe" CACHE STRING "Path to a program.")
SET(CMAKE_PLATFORM_INFO_INITIALIZED "1" CACHE STRING "Platform information initialized")
SET(CMAKE_PREFIX_PATH "C:/msys64/ucrt64" CACHE STRING "No help, variable specified on the command line.")
SET(CMAKE_PROJECT_DESCRIPTION "A parallel, three-dimensional PIC-DSMC solver and flexible particle-based plasma simulation suite" CACHE STRING "Value Computed by CMake")
SET(CMAKE_PROJECT_HOMEPAGE_URL "https://github.com/piclas-framework/piclas" CACHE STRING "Value Computed by CMake")
SET(CMAKE_PROJECT_NAME "PICLas" CACHE STRING "Value Computed by CMake")
SET(CMAKE_PROJECT_VERSION "4.1.0" CACHE STRING "Value Computed by CMake")
SET(CMAKE_PROJECT_VERSION_MAJOR "4" CACHE STRING "Value Computed by CMake")
SET(CMAKE_PROJECT_VERSION_MINOR "1" CACHE STRING "Value Computed by CMake")
SET(CMAKE_PROJECT_VERSION_PATCH "0" CACHE STRING "Value Computed by CMake")
SET(CMAKE_RANLIB "C:/msys64/ucrt64/bin/ranlib.exe" CACHE STRING "Path to a program.")
SET(CMAKE_RC_COMPILER "C:/msys64/ucrt64/bin/windres.exe" CACHE STRING "RC compiler")
SET(CMAKE_RC_COMPILER_WORKS "1" CACHE STRING "")
SET(CMAKE_READELF "C:/msys64/ucrt64/bin/readelf.exe" CACHE STRING "Path to a program.")
SET(CMAKE_ROOT "C:/msys64/ucrt64/share/cmake" CACHE STRING "Path to CMake installation.")
SET(CMAKE_SKIP_INSTALL_RPATH "NO" CACHE STRING "If set, runtime paths are not added when installing shared libraries, but are added when building.")
SET(CMAKE_SKIP_RPATH "NO" CACHE STRING "If set, runtime paths are not added when using shared libraries.")
SET(CMAKE_STRIP "C:/msys64/ucrt64/bin/strip.exe" CACHE STRING "Path to a program.")
SET(CMAKE_TAPI "CMAKE_TAPI-NOTFOUND" CACHE STRING "Path to a program.")
SET(CMAKE_VERBOSE_MAKEFILE "FALSE" CACHE STRING "If this value is on, makefiles will be generated without the .SILENT directive, and all commands will be echoed to the console during the make.  This is useful for debugging only. With Visual Studio IDE projects all commands are done without /nologo.")
OPTION(LIBS_BUILD_HDF5 "No help, variable specified on the command line." OFF)
OPTION(LIBS_BUILD_MATH_LIB "No help, variable specified on the command line." OFF)
OPTION(LIBS_BUILD_PETSC "No help, variable specified on the command line." OFF)
OPTION(LIBS_USE_MPI "No help, variable specified on the command line." OFF)
OPTION(LIBS_USE_PETSC "No help, variable specified on the command line." ON)
